import type { Metadata } from 'next'
import fontsConfig from '@/font/index';

import "@arco-design/web-react/dist/css/arco.css";
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={fontsConfig["zh-tw"]}>
      <body>{children}</body>
    </html>
  )
}
